### ISSUE TITLE
X310 not responding after load custom RFNoC FPGA image

### ISSUE THREAD

**Issue by ArtisticZhao** [EttusResearch/uhd#550]
## Issue Description ##
I've built an RFNoC OOT module following the video of [RFNoC 4 Workshop - GRCon 2020](https://www.youtube.com/watch?v=M9ntwQie9vs&t=3308s).

And I build the FPGA image on target X300_HG. But when I load the image to X310, the X310 network is not responding.
But I try to load the image from the JTAG via Xilinx Vivado toolchain, the image seems worked. I can run the `uhd_usrp_probe` and get the image details.

## Setup Details ##

UHD 4.1.0.5

Now I can use my RFNoC OOT module by the Jtag loaded image. How can I burn image to Flash? 

Thank you.

**Comment by wordimont** [comment]
You mentioned X300_HG but X310 device. Make sure you use the correct bitstream type for your device (X300_HG vs X310_HG).

Start by loading a known-good bitstream via JTAG, like the one downloaded by `uhd_images_downloader`. Make sure you can run `uhd_usrp_probe`.

Then you should be able to use `uhd_image_loader` to write a bitstream to flash, then cycle the power on the USRP to load the bitstream from flash. For example, for X310 you would run something like this:

`uhd_image_loader --args "type=x300,addr=192.168.10.2" --fpga-path ./build-X310_HG/x300.bit`

Make sure --fpga-path points to the correct working bitstream file you want to flash. Here are additional instructions on restoring the flash to a working state:

https://kb.ettus.com/X300/X310_Device_Recovery

**Comment by ArtisticZhao** [comment]
@wordimont Thank you for your reply.

I make sure I had built the image use the correct target X310_HG. The following is my `gain_x310_rfnoc_image_core.yml`:

```
# General parameters
# -----------------------------------------
schema: rfnoc_imagebuilder_args         # Identifier for the schema used to validate this file
copyright: ''                           # Copyright information used in file headers
license: 'SPDX-License-Identifier: LGPL-3.0-or-later' # License information used in file headers
version: '1.0'                            # File version
rfnoc_version: '1.0'                      # RFNoC protocol version
chdr_width: 64                          # Bit width of the CHDR bus for this image
device: 'x310'
default_target: 'X310_HG'

# A list of all stream endpoints in design
# ----------------------------------------
stream_endpoints:
  ep0:                       # Stream endpoint name
    ctrl: True                      # Endpoint passes control traffic
    data: True                      # Endpoint passes data traffic
    buff_size: 32768                # Ingress buffer size for data
  ep1:                       # Stream endpoint name
    ctrl: False                     # Endpoint passes control traffic
    data: True                      # Endpoint passes data traffic
    buff_size: 0                    # Ingress buffer size for data
  ep2:                       # Stream endpoint name
    ctrl: False                     # Endpoint passes control traffic
    data: True                      # Endpoint passes data traffic
    buff_size: 32768                # Ingress buffer size for data
  ep3:                       # Stream endpoint name
    ctrl: False                     # Endpoint passes control traffic
    data: True                      # Endpoint passes data traffic
    buff_size: 0                    # Ingress buffer size for data
  ep4:                       # Stream endpoint name
    ctrl: False                     # Endpoint passes control traffic
    data: True                      # Endpoint passes data traffic
    buff_size: 32768                # Ingress buffer size for data

# A list of all NoC blocks in design
# ----------------------------------
noc_blocks:
  duc0:                      # NoC block name
    block_desc: 'duc.yml'    # Block device descriptor file
    parameters:
      NUM_PORTS: 1
  ddc0:
    block_desc: 'ddc.yml'
    parameters:
      NUM_PORTS: 2
  radio0:
    block_desc: 'radio_2x64.yml'
  duc1:
    block_desc: 'duc.yml'
    parameters:
      NUM_PORTS: 1
  ddc1:
    block_desc: 'ddc.yml'
    parameters:
      NUM_PORTS: 2
  radio1:
    block_desc: 'radio_2x64.yml'
  gain0:
    block_desc: 'gain.yml'

# A list of all static connections in design
# ------------------------------------------
# Format: A list of connection maps (list of key-value pairs) with the following keys
#         - srcblk  = Source block to connect
#         - srcport = Port on the source block to connect
#         - dstblk  = Destination block to connect
#         - dstport = Port on the destination block to connect
connections:
  # ep0 to radio0(0) - RFA TX
  - { srcblk: ep0,    srcport: out0,  dstblk: duc0,   dstport: in_0 }
  - { srcblk: duc0,   srcport: out_0, dstblk: radio0, dstport: in_0 }
  # radio0(0) to ep0 - RFA RX
  - { srcblk: radio0, srcport: out_0, dstblk: ddc0,   dstport: in_0 }
  - { srcblk: ddc0,   srcport: out_0, dstblk: ep0,    dstport: in0  }
  # radio0(1) to ep1 - RFA RX
  - { srcblk: radio0, srcport: out_1, dstblk: ddc0,   dstport: in_1 }
  - { srcblk: ddc0,   srcport: out_1, dstblk: ep1,    dstport: in0  }
  # ep2 to radio1(0) - RFB TX
  - { srcblk: ep2,    srcport: out0,  dstblk: duc1,   dstport: in_0 }
  - { srcblk: duc1,   srcport: out_0, dstblk: radio1, dstport: in_0 }
  # radio1(0) to ep2 - RFB RX
  - { srcblk: radio1, srcport: out_0, dstblk: ddc1,   dstport: in_0 }
  - { srcblk: ddc1,   srcport: out_0, dstblk: ep2,    dstport: in0  }
  # radio1(1) to ep3 - RFB RX
  - { srcblk: radio1, srcport: out_1, dstblk: ddc1,   dstport: in_1 }
  - { srcblk: ddc1,   srcport: out_1, dstblk: ep3,    dstport: in0  }
  # Custom block connection: ep4 to gain0 and gain0 to ep4
  - { srcblk: ep4, srcport: out0, dstblk: gain0, dstport: in }
  - { srcblk: gain0, srcport: out, dstblk: ep4, dstport: in0 }
  # BSP Connections
  - { srcblk: radio0, srcport: ctrl_port, dstblk: _device_, dstport: ctrlport_radio0 }
  - { srcblk: radio1, srcport: ctrl_port, dstblk: _device_, dstport: ctrlport_radio1 }
  - { srcblk: _device_, srcport: x300_radio0, dstblk: radio0, dstport: x300_radio }
  - { srcblk: _device_, srcport: x300_radio1, dstblk: radio1, dstport: x300_radio }
  - { srcblk: _device_, srcport: time_keeper, dstblk: radio0, dstport: time_keeper }
  - { srcblk: _device_, srcport: time_keeper, dstblk: radio1, dstport: time_keeper }

# A list of all clock domain connections in design
# ------------------------------------------
# Format: A list of connection maps (list of key-value pairs) with the following keys
#         - srcblk  = Source block to connect (Always "_device"_)
#         - srcport = Clock domain on the source block to connect
#         - dstblk  = Destination block to connect
#         - dstport = Clock domain on the destination block to connect
clk_domains:
    - { srcblk: _device_, srcport: radio, dstblk: radio0, dstport: radio }
    - { srcblk: _device_, srcport: ce,    dstblk: ddc0,   dstport: ce    }
    - { srcblk: _device_, srcport: ce,    dstblk: duc0,   dstport: ce    }
    - { srcblk: _device_, srcport: radio, dstblk: radio1, dstport: radio }
    - { srcblk: _device_, srcport: ce,    dstblk: ddc1,   dstport: ce    }
    - { srcblk: _device_, srcport: ce,    dstblk: duc1,   dstport: ce    }
    - { srcblk: _device_, srcport: ce,    dstblk: gain0, dstport: ce }

```
I built the image via:
```
rfnoc_image_builder -F ~/Downloads/tmp/uhd/fpga -I ~/Playground/rfnoc/rfnoc-demogain -y ./rfnoc/icores/gain_x310_rfnoc_image_core.yml -l debug
```
I find image file on `/home/lilacsat/Downloads/tmp/uhd/fpga/usrp3/top/x300/build-X310_HG/x300.bit`

And I upload the image .bit file by Vivado hardware manger through the JTAG. It worked (I can `uhd_usrp_probe` and run GNURadio flowgraph which contain the RFNoC block I create).

But I burn the image use the `uhd_image_loader --args="type=x300,addr=192.168.40.2" --fpga-path=/home/lilacsat/Downloads/tmp/uhd/fpga/usrp3/top/x300/build-X310_HG/x300.bit`. When I cycled the power on X310, I seems like SFP not work. My PC cannot detect the connection from the X310.

Do you have any ideas? Thank you again.

Regards.
