### ISSUE TITLE
rfnoc_create_verilog.py module I/O port in RFNoC >=4.0

### ISSUE THREAD

**Issue by andreaskuster** [EttusResearch/uhd#605]
## Issue Description ##
Generating the custom block according to [Getting_Started_with_RFNoC_in_UHD_4.0](https://kb.ettus.com/Getting_Started_with_RFNoC_in_UHD_4.0) with the command: `python3 $UHD_DIR/host/utils/rfnoc_blocktool/rfnoc_create_verilog.py -c test.yml -d ./test` on the example `test.yml` file results in a generated block without the AXI DRAM Slave signals (AXI memory mapped interface) integrated.

I tried to add it manually, with limited success. Somehow, for small designs, the memory mapped interface seems to work well, however as soon as my custom block increases in complexity (high LUT and DSP utilization), the bitstream gets created successful without errors, but the AXI interface does not seem to respond.

## Setup Details ##
Tested on `uhd 4.2.0.0`, `ubuntu 20.04`, `python3.8`

## Expected Behavior ##
```
module rfnoc_block_test #(
  parameter [9:0] THIS_PORTID     = 10'd0,
  parameter       CHDR_W          = 64,
  parameter [5:0] MTU             = 10,
  parameter       NUM_PORTS_IN    = 2,
  parameter       NUM_PORTS_OUT   = 2,
  parameter       MEM_DATA_W      = 64,
  parameter       MEM_ADDR_W      = 30
)(
  // RFNoC Framework Clocks and Resets
  input  wire                   rfnoc_chdr_clk,
  input  wire                   rfnoc_ctrl_clk,
  input  wire                   mem_clk,
  // RFNoC Backend Interface
  input  wire [511:0]           rfnoc_core_config,
  output wire [511:0]           rfnoc_core_status,
  // AXIS-CHDR Input Ports (from framework)
  input  wire [(0+NUM_PORTS_IN)*CHDR_W-1:0] s_rfnoc_chdr_tdata,
  input  wire [(0+NUM_PORTS_IN)-1:0]        s_rfnoc_chdr_tlast,
  input  wire [(0+NUM_PORTS_IN)-1:0]        s_rfnoc_chdr_tvalid,
  output wire [(0+NUM_PORTS_IN)-1:0]        s_rfnoc_chdr_tready,
  // AXIS-CHDR Output Ports (to framework)
  output wire [(0+NUM_PORTS_OUT)*CHDR_W-1:0] m_rfnoc_chdr_tdata,
  output wire [(0+NUM_PORTS_OUT)-1:0]        m_rfnoc_chdr_tlast,
  output wire [(0+NUM_PORTS_OUT)-1:0]        m_rfnoc_chdr_tvalid,
  input  wire [(0+NUM_PORTS_OUT)-1:0]        m_rfnoc_chdr_tready,
  // AXIS-Ctrl Input Port (from framework)
  input  wire [31:0]            s_rfnoc_ctrl_tdata,
  input  wire                   s_rfnoc_ctrl_tlast,
  input  wire                   s_rfnoc_ctrl_tvalid,
  output wire                   s_rfnoc_ctrl_tready,
  // AXIS-Ctrl Output Port (to framework)
  output wire [31:0]            m_rfnoc_ctrl_tdata,
  output wire                   m_rfnoc_ctrl_tlast,
  output wire                   m_rfnoc_ctrl_tvalid,
  input  wire                   m_rfnoc_ctrl_tready,

 //---------------------------------------------------------------------------
  // AXI Memory Mapped Interface
  //---------------------------------------------------------------------------

  // AXI Interface Clock and Reset
  input wire mem_clk,
  input wire axi_rst,

  // AXI Write address channel
  output wire [           (NUM_PORTS*1)-1:0] m_axi_awid,
  output wire [  (NUM_PORTS*MEM_ADDR_W)-1:0] m_axi_awaddr,
  output wire [           (NUM_PORTS*8)-1:0] m_axi_awlen,
  output wire [           (NUM_PORTS*3)-1:0] m_axi_awsize,
  output wire [           (NUM_PORTS*2)-1:0] m_axi_awburst,
  output wire [           (NUM_PORTS*1)-1:0] m_axi_awlock,
  output wire [           (NUM_PORTS*4)-1:0] m_axi_awcache,
  output wire [           (NUM_PORTS*3)-1:0] m_axi_awprot,
  output wire [           (NUM_PORTS*4)-1:0] m_axi_awqos,
  output wire [           (NUM_PORTS*4)-1:0] m_axi_awregion,
  output wire [           (NUM_PORTS*1)-1:0] m_axi_awuser,
  output wire [           (NUM_PORTS*1)-1:0] m_axi_awvalid,
  input  wire [           (NUM_PORTS*1)-1:0] m_axi_awready,
  // AXI Write data channel
  output wire [  (NUM_PORTS*MEM_DATA_W)-1:0] m_axi_wdata,
  output wire [(NUM_PORTS*MEM_DATA_W/8)-1:0] m_axi_wstrb,
  output wire [           (NUM_PORTS*1)-1:0] m_axi_wlast,
  output wire [           (NUM_PORTS*1)-1:0] m_axi_wuser,
  output wire [           (NUM_PORTS*1)-1:0] m_axi_wvalid,
  input  wire [           (NUM_PORTS*1)-1:0] m_axi_wready,
  // AXI Write response channel signals
  input  wire [           (NUM_PORTS*1)-1:0] m_axi_bid,
  input  wire [           (NUM_PORTS*2)-1:0] m_axi_bresp,
  input  wire [           (NUM_PORTS*1)-1:0] m_axi_buser,
  input  wire [           (NUM_PORTS*1)-1:0] m_axi_bvalid,
  output wire [           (NUM_PORTS*1)-1:0] m_axi_bready,
  // AXI Read address channel
  output wire [           (NUM_PORTS*1)-1:0] m_axi_arid,
  output wire [  (NUM_PORTS*MEM_ADDR_W)-1:0] m_axi_araddr,
  output wire [           (NUM_PORTS*8)-1:0] m_axi_arlen,
  output wire [           (NUM_PORTS*3)-1:0] m_axi_arsize,
  output wire [           (NUM_PORTS*2)-1:0] m_axi_arburst,
  output wire [           (NUM_PORTS*1)-1:0] m_axi_arlock,
  output wire [           (NUM_PORTS*4)-1:0] m_axi_arcache,
  output wire [           (NUM_PORTS*3)-1:0] m_axi_arprot,
  output wire [           (NUM_PORTS*4)-1:0] m_axi_arqos,
  output wire [           (NUM_PORTS*4)-1:0] m_axi_arregion,
  output wire [           (NUM_PORTS*1)-1:0] m_axi_aruser,
  output wire [           (NUM_PORTS*1)-1:0] m_axi_arvalid,
  input  wire [           (NUM_PORTS*1)-1:0] m_axi_arready,
  // AXI Read data channel
  input  wire [           (NUM_PORTS*1)-1:0] m_axi_rid,
  input  wire [  (NUM_PORTS*MEM_DATA_W)-1:0] m_axi_rdata,
  input  wire [           (NUM_PORTS*2)-1:0] m_axi_rresp,
  input  wire [           (NUM_PORTS*1)-1:0] m_axi_rlast,
  input  wire [           (NUM_PORTS*1)-1:0] m_axi_ruser,
  input  wire [           (NUM_PORTS*1)-1:0] m_axi_rvalid,
  output wire [           (NUM_PORTS*1)-1:0] m_axi_rready
);
```

## Actual Behaviour ##
```
module rfnoc_block_test #(
  parameter [9:0] THIS_PORTID     = 10'd0,
  parameter       CHDR_W          = 64,
  parameter [5:0] MTU             = 10,
  parameter       NUM_PORTS_IN    = 2,
  parameter       NUM_PORTS_OUT   = 2,
  parameter       MEM_DATA_W      = 64,
  parameter       MEM_ADDR_W      = 30
)(
  // RFNoC Framework Clocks and Resets
  input  wire                   rfnoc_chdr_clk,
  input  wire                   rfnoc_ctrl_clk,
  input  wire                   mem_clk,
  // RFNoC Backend Interface
  input  wire [511:0]           rfnoc_core_config,
  output wire [511:0]           rfnoc_core_status,
  // AXIS-CHDR Input Ports (from framework)
  input  wire [(0+NUM_PORTS_IN)*CHDR_W-1:0] s_rfnoc_chdr_tdata,
  input  wire [(0+NUM_PORTS_IN)-1:0]        s_rfnoc_chdr_tlast,
  input  wire [(0+NUM_PORTS_IN)-1:0]        s_rfnoc_chdr_tvalid,
  output wire [(0+NUM_PORTS_IN)-1:0]        s_rfnoc_chdr_tready,
  // AXIS-CHDR Output Ports (to framework)
  output wire [(0+NUM_PORTS_OUT)*CHDR_W-1:0] m_rfnoc_chdr_tdata,
  output wire [(0+NUM_PORTS_OUT)-1:0]        m_rfnoc_chdr_tlast,
  output wire [(0+NUM_PORTS_OUT)-1:0]        m_rfnoc_chdr_tvalid,
  input  wire [(0+NUM_PORTS_OUT)-1:0]        m_rfnoc_chdr_tready,
  // AXIS-Ctrl Input Port (from framework)
  input  wire [31:0]            s_rfnoc_ctrl_tdata,
  input  wire                   s_rfnoc_ctrl_tlast,
  input  wire                   s_rfnoc_ctrl_tvalid,
  output wire                   s_rfnoc_ctrl_tready,
  // AXIS-Ctrl Output Port (to framework)
  output wire [31:0]            m_rfnoc_ctrl_tdata,
  output wire                   m_rfnoc_ctrl_tlast,
  output wire                   m_rfnoc_ctrl_tvalid,
  input  wire                   m_rfnoc_ctrl_tready
);
```

## Steps to reproduce the problem ##

test.yml:
```
schema: rfnoc_modtool_args
module_name: test
version: "1.0"
rfnoc_version: "1.0"
chdr_width: 64
noc_id: 0x00000011


parameters:
  NUM_PORTS_IN: 2
  NUM_PORTS_OUT: 2
  MEM_DATA_W: 64
  MEM_ADDR_W: 30

clocks:
  - name: rfnoc_chdr
    freq: "[]"
  - name: rfnoc_ctrl
    freq: "[]"  
  - name: mem
    freq: "[]"

control:
  fpga_iface: ctrlport
  interface_direction: slave
  fifo_depth: 32
  clk_domain: rfnoc_chdr
  ctrlport:
    byte_mode: False
    timed: False
    has_status: False

data:
  fpga_iface: axis_data
  clk_domain: rfnoc_chdr
  inputs:
    in:
      num_ports: NUM_PORTS_IN
      item_width: 32
      nipc: 1 
      info_fifo_depth: 32
      payload_fifo_depth: 32
      format: sc16
      mdata_sig: ~

  outputs:
    out:
      num_ports: NUM_PORTS_OUT
      item_width: 32
      nipc: 1
      info_fifo_depth: 32
      payload_fifo_depth: 32
      sideband_at_end: True
      format: sc16
      mdata_sig: ~

io_ports:
  axi_ram:
    type: axi4_mm
    drive: master

registers:

properties:

```
